kubeconfig_file_path: "./tmp/kubeconfig.yaml"

generations: 20
population_size: 4

fitness_function: 
  query: 'max_over_time(container_cpu_usage_seconds_total{namespace="robot-shop", container="mysql"}[$range$])'
  type: range

scenario:
  pod-scenarios:
    namespace:
      - robot-shop
    pod_label:
      - service=mysql
      - service=redis
      - service=cart
      - service=mongodb

  application-outages:
    namespace:
      - robot-shop
    pod_selector:
      - "{service: mysql}"
      - "{service: redis}"
      - "{service: cart}"
      - "{service: mongodb}"

  node-cpu-hog:
    taints:
      - '[]'
    node_selector:
      - ""

  node-memory-hog:
    taints:
      - '[]'
    node_selector:
      - ""
