kubeconfig_file_path: "./tmp/kubeconfig.yaml"

generations: 2
population_size: 10

fitness_function: 'sum(kube_pod_container_status_restarts_total{namespace="robot-shop"})'

scenario:
  container-scenarios:
    namespace:
    - openshift-dns
    label_selector:
    - dns.operator.openshift.io/daemonset-dns=default
    container_name:
    - dns
    - kube-rbac-proxy

  node-cpu-hog:
    taints:
      - '[]'
    node_selector:
      - ""

  node-memory-hog:
    taints:
      - '[]'
    node_selector:
      - ""
