kubeconfig_file_path: "./tmp/kubeconfig.yaml"

generations: 5
population_size: 4

fitness_function: 
  query: 'sum(kube_pod_container_status_restarts_total{namespace="robot-shop"})'
  type: point
  include_krkn_failure: true


scenario:
  pod-scenarios:
    namespace:
      - robot-shop
    pod_label:
      - service=mysql
      - service=redis
      - service=cart
      - service=mongodb
      - service=rabbitmq
      - service=user
      - service=shipping

  application-outages:
    namespace:
      - robot-shop
    pod_selector:
      - "{service: mysql}"
      - "{service: redis}"
      - "{service: cart}"
      - "{service: mongodb}"
      - "{service: user}"
      - "{service: shipping}"
      - "{service: rabbitmq}"

  container-scenarios:
    namespace:
    - openshift-dns
    label_selector:
    - dns.operator.openshift.io/daemonset-dns=default
    container_name:
    - dns
    - kube-rbac-proxy

  node-cpu-hog:
    taints:
      - '[]'
    node_selector:
      - ""

  node-memory-hog:
    taints:
      - '[]'
    node_selector:
      - ""
