kubeconfig_file_path: "./tmp/kubeconfig.yaml"

generations: 2
population_size: 2
composition_rate: 0
population_injection_rate: 0

fitness_function: 
  query: 'sum(kube_pod_container_status_restarts_total{namespace="robot-shop"})'
  type: point
  include_krkn_failure: true

health_checks:
  - name: cart
    url: "$HOST/cart/add/1/Watson/1"
  - name: catalogue
    url: "$HOST/catalogue/categories"
  - name: shipping
    url: "$HOST/shipping/codes"
  - name: payment
    url: "$HOST/payment/health"
  - name: user
    url: "$HOST/user/uniqueid"
  - name: ratings
    url: "$HOST/ratings/api/fetch/Watson"


scenario:
  pod-scenarios:
    namespace:
      - robot-shop
    pod_label:
      - service=mongodb
      - service=mysql
      - service=redis
      - service=cart
      - service=rabbitmq
      - service=user
      - service=shipping
      - service=payment
      - service=catalogue
