kubeconfig_file_path: "./tmp/kubeconfig.yaml"

generations: 1
population_size: 2

fitness_function: 'sum(kube_pod_container_status_restarts_total{namespace="robot-shop"})'

scenario:
  pod-scenarios:
    namespace:
      - robot-shop
    pod_label:
      - service=mysql
      - service=redis
      - service=cart
      - service=mongodb
      - service=rabbitmq
      - service=user
      - service=shipping
    
  application-outages:
    namespace:
      - robot-shop
    pod_selector:
      - "{service: mysql}"
      - "{service: redis}"
      - "{service: cart}"
      - "{service: mongodb}"
      - "{service: user}"
      - "{service: shipping}"
      - "{service: rabbitmq}"

